name: React CI/CD Pipeline

on:
    push:
        branches: [ main ]

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        
        steps:
            - name: checkout code
              uses: actions/checkout@v4
            - name: setup node
              uses: actions/setup-node@v2
              with:
                node-version: '22'
            
            - name: installing dependencies
              run: npm install
            - name: Run Tests
              run: npm test -- --watchAll=false
            
            - name: Build
              run: npm run build
